using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace KillerApps.Emulation.Atari.Lynx
{
	internal class UartTimerLogic: ClockedTimerLogic
	{
		public UartTimerLogic(Timer owner): base(owner) { }

		public override int Multiplier
		{
			// "The baud rate is generated by TIMER4 according to the equation
			// CLOCK4 / (TIMER4 + 1) / 8"
			// Additional divide by 8 requires shifting right 3 extra bits
			get { return 4 + 3 + (int)Owner.StaticControlBits.SourcePeriod; }
		}
	}
}
