//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KillerApps.Gaming.Atari {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Roms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Roms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KillerApps.Gaming.Atari.Roms", typeof(Roms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Collision {
            get {
                object obj = ResourceManager.GetObject("Collision", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demo01 {
            get {
                object obj = ResourceManager.GetObject("Demo01", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demo02 {
            get {
                object obj = ResourceManager.GetObject("Demo02", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demo03 {
            get {
                object obj = ResourceManager.GetObject("Demo03", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demo04 {
            get {
                object obj = ResourceManager.GetObject("Demo04", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Demo05 {
            get {
                object obj = ResourceManager.GetObject("Demo05", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IRQ_Test {
            get {
                object obj = ResourceManager.GetObject("IRQ_Test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Lite {
            get {
                object obj = ResourceManager.GetObject("Lite", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LYNXBOOT {
            get {
                object obj = ResourceManager.GetObject("LYNXBOOT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Mode7 {
            get {
                object obj = ResourceManager.GetObject("Mode7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Wuerfel {
            get {
                object obj = ResourceManager.GetObject("Wuerfel", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
